# Group by and Aggregate Functions

Simple exercise based on [https://github.com/AlexTheAnalyst/PandasYouTubeSeries](https://github.com/AlexTheAnalyst/PandasYouTubeSeries)

*Visualisation Tip*
If you prefer the Jupyter Notebook render over VS Code's data wrangler, you can disable the `data wrangler output viewer` option in the settings. 
See [https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html](https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html) for more details.

In [4]:
## As always, import pandas as ...

import pandas as pd

In [5]:
## Read CSV from GitHub url: https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Flavors.csv?raw=true

df = pd.read_csv("https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Flavors.csv?raw=true")

In [7]:
## Explore the data
df.head()
df.shape
df.info
df
## Success? Commit changes to the repository!

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [8]:
## Let's group by Base Flavor

df.groupby("Base Flavor").mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [ ]:
## Make this a new datafram



## Success? Commit changes to the repository!

In [ ]:
## Let's count the number of flavors for each Base Flavor

In [ ]:
## Let's get the means for each Base Flavor



## Success? Commit changes to the repository!

In [ ]:
## Let's try that in one line

In [ ]:
## Let's discover some popular aggregate statistics like count, sum, min, max. Notice that text columns will appear with min and max as well



## Success? Commit changes to the repository!

In [ ]:
## Let's try more advanced aggregation with the `agg` function
## We have to specify which columns we want to aggregate and which functions to apply to them via a dictionary



## Success? Commit changes to the repository!

In [ ]:
## Let's group on multiple columns
## Check the dataframe again and group by Base Flavor and Liked (and show mean as value)

In [ ]:
# Do the multiple aggregation for Base Flavor and Liked

In [ ]:
## Success? Commit changes to the repository!

In [ ]:
## Let's disover an easier way to analyze the grouped data quickly

In [ ]:
## Success? Commit changes and push the repository to GitHub!